# Generated by Django 5.0.2 on 2024-02-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(unique=True)),
                ("product_name", models.CharField(max_length=100)),
                ("product_brand", models.CharField(max_length=50)),
                ("product_mfg_year", models.DateField()),
                ("product_image_url", models.URLField(max_length=500)),
                (
                    "product_url",
                    models.URLField(default="http://ornax.com/", max_length=600),
                ),
                ("product_stock", models.IntegerField()),
                ("product_price", models.IntegerField()),
                ("product_description", models.CharField(max_length=300)),
            ],
        ),
    ]
